# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IuEl6vg9tQgm94kTFP-hRGtkWviaIR4k
"""

!pip install -q transformers==4.47.0

!pip install -q datasets

!pip install -q peft==0.13.2

!pip install -q trl==0.12.2

!pip install -q bitsandbytes>=0.43.0

!pip install -q accelerate>=0.26.0

# ==============================
# CELL 2 — Verify environment
# ==============================
import torch
import transformers, peft, trl, bitsandbytes, accelerate

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")
print("transformers:", transformers.__version__)
print("peft:", peft.__version__)
print("trl:", trl.__version__)
print("bitsandbytes:", bitsandbytes.__version__)
print("accelerate:", accelerate.__version__)

# ==============================
# CELL 3 — Main training code
# ==============================
import json
import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
    prepare_model_for_kbit_training
)
from trl import SFTTrainer, SFTConfig

# ----------------------------
# 1. Model + tokenizer
# ----------------------------
model_name = "Qwen/Qwen2.5-0.5B-Instruct"
output_dir = "/content/drive/MyDrive/qwen_task1"

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# ----------------------------
# 2. Prepare for QLoRA
# ----------------------------
model = prepare_model_for_kbit_training(model)
model.gradient_checkpointing_enable()
model.config.use_cache = False

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ]
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ----------------------------
# 3. Load dataset
# ----------------------------
dataset = load_dataset(
    "json",
    data_files={
        "train": "task1_train.jsonl",
        "validation": "task1_val.jsonl"
    }
)

# ----------------------------
# 4. Format dataset
# ----------------------------
def format_example(example):
    messages = [
        {
            "role": "system",
            "content": "You are a clinical information extraction assistant. Output ONLY valid JSON."
        },
        {
            "role": "user",
            "content": example["input"]
        },
        {
            "role": "assistant",
            "content": json.dumps(example["output"], ensure_ascii=False)
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

train_ds = dataset["train"].map(format_example)
val_ds = dataset["validation"].map(format_example)

train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col != "text"])
val_ds = val_ds.remove_columns([col for col in val_ds.column_names if col != "text"])

# ----------------------------
# 5. SFTConfig (replaces TrainingArguments)
# ----------------------------
sft_config = SFTConfig(
    output_dir=output_dir,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    num_train_epochs=3,
    fp16=True,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="epoch",         # fixed: was evaluation_strategy
    save_total_limit=2,
    report_to="none",
    optim="paged_adamw_8bit",
    max_seq_length=1024,           # fixed: moved from SFTTrainer
    dataset_text_field="text",     # fixed: moved from SFTTrainer
)

# ----------------------------
# 6. Trainer
# ----------------------------
trainer = SFTTrainer(
    model=model,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    args=sft_config,
    processing_class=tokenizer,
)

# ----------------------------
# 7. Train
# ----------------------------
trainer.train()

# ----------------------------
# 8. Save adapter + tokenizer
# ----------------------------
trainer.model.save_pretrained(f"{output_dir}/final_adapter")
tokenizer.save_pretrained(f"{output_dir}/final_adapter")

!pip install -U trl transformers accelerate bitsandbytes peft

# ==============================
# CELL 3 — Main training code
# ==============================
import json
import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)
from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
    prepare_model_for_kbit_training
)
from trl import SFTTrainer, SFTConfig

# ----------------------------
# 1. Model + tokenizer
# ----------------------------
model_name = "Qwen/Qwen2.5-0.5B-Instruct"
output_dir = "/content/drive/MyDrive/qwen_task1"

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# ----------------------------
# 2. Prepare for QLoRA
# ----------------------------
model = prepare_model_for_kbit_training(model)
model.gradient_checkpointing_enable()
model.config.use_cache = False

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ]
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ----------------------------
# 3. Load dataset
# ----------------------------
dataset = load_dataset(
    "json",
    data_files={
        "train": "task1_train.jsonl",
        "validation": "task1_val.jsonl"
    }
)

# ----------------------------
# 4. Format dataset
# ----------------------------
def format_example(example):
    messages = [
        {
            "role": "system",
            "content": "You are a clinical information extraction assistant. Output ONLY valid JSON."
        },
        {
            "role": "user",
            "content": example["input"]
        },
        {
            "role": "assistant",
            "content": json.dumps(example["output"], ensure_ascii=False)
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

train_ds = dataset["train"].map(format_example)
val_ds = dataset["validation"].map(format_example)

train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col != "text"])
val_ds = val_ds.remove_columns([col for col in val_ds.column_names if col != "text"])

# ----------------------------
# 5. SFTConfig (replaces TrainingArguments)
# ----------------------------
sft_config = SFTConfig(
    output_dir=output_dir,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,
    num_train_epochs=3,
    bf16=True,
    fp16=False,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    save_total_limit=2,
    report_to="none",
    optim="paged_adamw_8bit",
    dataset_text_field="text",
    max_length=1024,
    max_grad_norm=0.0,
)

# ----------------------------
# 6. Trainer
# ----------------------------
trainer = SFTTrainer(
    model=model,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    args=sft_config,
    processing_class=tokenizer,
)

# ----------------------------
# 7. Train
# ----------------------------
trainer.train()

# ----------------------------
# 8. Save adapter + tokenizer
# ----------------------------
trainer.model.save_pretrained(f"{output_dir}/final_adapter")
tokenizer.save_pretrained(f"{output_dir}/final_adapter")

import os

print(os.listdir("/content"))

import trl
print(trl.__version__)

import inspect
from trl import SFTTrainer
print(inspect.signature(SFTTrainer.__init__))

import torch
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_bf16_supported())

import json
import torch
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig
)
from peft import (
    LoraConfig,
    get_peft_model,
    TaskType,
    prepare_model_for_kbit_training,
    PeftModel
)
from trl import SFTTrainer, SFTConfig

# ----------------------------
# 1. Model + tokenizer
# ----------------------------
model_name = "Qwen/Qwen2.5-0.5B-Instruct"
task1_adapter_path = "/content/drive/MyDrive/qwen_task1/final_adapter"
output_dir = "/content/drive/MyDrive/qwen_task2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

# ----------------------------
# 2. Prepare for QLoRA
# ----------------------------
base_model = prepare_model_for_kbit_training(base_model)
base_model.gradient_checkpointing_enable()
base_model.config.use_cache = False

# ----------------------------
# 3. Load Task 1 adapter
# ----------------------------
model = PeftModel.from_pretrained(base_model, task1_adapter_path)

# If you want to continue training the same adapter, this is enough.
# If needed, you can inspect trainable params:
model.print_trainable_parameters()

# ----------------------------
# 4. Load Task 2 dataset
# ----------------------------
dataset = load_dataset(
    "json",
    data_files={
        "train": "task2_train.jsonl",
        "validation": "task2_val.jsonl"
    }
)

def format_example(example):
    messages = [
        {
            "role": "system",
            "content": "You are an emergency triage assistant. Output ONLY valid JSON with esi_level and reason."
        },
        {
            "role": "user",
            "content": json.dumps(example["input"], ensure_ascii=False)
        },
        {
            "role": "assistant",
            "content": json.dumps(example["output"], ensure_ascii=False)
        }
    ]
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False
    )
    return {"text": text}

train_ds = dataset["train"].map(format_example)
val_ds = dataset["validation"].map(format_example)

train_ds = train_ds.remove_columns([col for col in train_ds.column_names if col != "text"])
val_ds = val_ds.remove_columns([col for col in val_ds.column_names if col != "text"])

# ----------------------------
# 5. Training config
# ----------------------------
sft_config = SFTConfig(
    output_dir=output_dir,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=1e-4,
    num_train_epochs=2,
    bf16=True,
    fp16=False,
    logging_steps=10,
    save_strategy="epoch",
    eval_strategy="epoch",
    save_total_limit=2,
    report_to="none",
    optim="paged_adamw_8bit",
    dataset_text_field="text",
    max_length=768,
    max_grad_norm=0.0
)

# ----------------------------
# 6. Trainer
# ----------------------------
trainer = SFTTrainer(
    model=model,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    args=sft_config,
    processing_class=tokenizer
)

# ----------------------------
# 7. Train
# ----------------------------
trainer.train()

# ----------------------------
# 8. Save adapter + tokenizer
# ----------------------------
trainer.model.save_pretrained(f"{output_dir}/final_adapter")
tokenizer.save_pretrained(f"{output_dir}/final_adapter")

from google.colab import drive
drive.mount('/content/drive')

def predict(text):
    messages = [
        {
            "role": "system",
            "content": "You are an emergency triage assistant. Output ONLY valid JSON with esi_level and reason."
        },
        {
            "role": "user",
            "content": text
        }
    ]
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=120,
            do_sample=False
        )

    return tokenizer.decode(out[0], skip_special_tokens=True)

sample = {
    "age": 46,
    "sex": "male",
    "chief_complaint": "sore throat and cough",
    "vitals": {"bp": "112/82", "hr": 77, "temp_f": 101.8, "spo2": 92},
    "pmh": ["asthma"],
    "presentation": "speaking in short sentences",
    "duration": "67 hours"
}

print(predict(json.dumps(sample)))